---
- name: Build and deploy Java Tomcat app on Minikube
  hosts: localhost
  vars:
    project_path: "{{ lookup('env', 'WORKSPACE') | default('../', true) }}"
    image_name: my-app
    deployment_name: depl-myapp
    service_name: myapp-svc
    namespace: default

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: build
        build:
          path: "{{ project_path }}"

    - name: Delete existing Kubernetes deployment (if any)
      shell: |
        kubectl delete deployment {{ deployment_name }} --namespace {{ namespace }} --ignore-not-found
      args:
        executable: /bin/bash

    - name: Delete existing Kubernetes service (if any)
      shell: |
        kubectl delete service {{ service_name }} --namespace {{ namespace }} --ignore-not-found
      args:
        executable: /bin/bash

    - name: Apply new Kubernetes deployment and service
      shell: |
        kubectl apply -f {{ project_path }}/ansible/deployment.yaml
      args:
        executable: /bin/bash
