---
- name: Build and deploy Java Tomcat app on Minikube
  hosts: localhost
  vars:
    project_path: "{{ lookup('env', 'WORKSPACE') | default('../', true) }}"
    image_name: my-app
    deployment_name: depl-myapp
    service_name: myapp-svc
    namespace: default

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: latest
        source: build
        build:
          path: "{{ project_path }}"

    - name: Apply new Kubernetes deployment and service
      shell: |
        kubectl apply -f {{ project_path }}/k8s/deployment.yaml
      args:
        executable: /bin/bash
      environment:
       KUBECONFIG: /var/lib/jenkins/.kube/config